export const CHANGE_INPUT_VALUE = "CHANGE_INPUT_VALUE";

export const UPDATE_RESULT = "UPDATE_RESULT";

export const CHANGE_FIRST_CURRENCY = "CHANGE_FIRST_CURRENCY";

export const CHANGE_SECOND_CURRECNY = "CHANGE_SECOND_CURRECNY";
